version: '3.2'

services:
  python:
    restart: always
    image: storedistance/python:1.0
    build: .
    container_name: 'storedistance'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes: 
      - ../src:/tmp/work
    